baseURL: https://kouhoumed.com/
languageCode: en-us
build:
  writeStats: true
markup:
  goldmark:
    renderer:
      unsafe: true

# Add this section to enable processing of image resources
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart

# Add this to specify where Hugo should look for image files
staticDir:
  - static
  - images

params:
  title: Mohamed Kouhou's personal website
  author: Mohamed Kouhou
  description: Website title
  copyright: >-
    Powered by [Hugo](https://gohugo.io/) & deployed on
    [GitHub Pages](https://pages.github.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">


  profile:
    name: "Mohamed Kouhou"
    tagline: Data Engineer
    location: "Paris, France"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/mkouhou/"
        title: LinkedIn
      - icon: fab fa-stack-overflow
        url: "https://stackoverflow.com/users/13006431/michael-kohen"
        title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/KouhouMed"
        title: GitHub
      - icon: fab fa-twitter
        url: "https://x.com/kouhou_mohamed"
        title: Twitter
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Graduated in MIAGE Business Intelligence from the University of Paris Dauphine with a solid background in artificial intelligence from ENSEIRB-MATMECA, I have significant expertise in data analysis, data integration solutions, and data modeling. My professional experience includes roles in data analysis at Ligentec and data engineering at Société Générale where I worked with data engineers and architects on various stages of the data pipeline, including data acquisition, integration, and real-time analysis.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Retail Banking Data Apprenticeship
        dates: Oct 2022 - Sept 2023
        url: "https://www.societegenerale.com/en"
        company: Société Générale
        #details: |1-
        #  - Printed from desktop. Sent [emails](#).
        #      - Called people *using* telephone.
        #  - Drank water from office cooler.
        #  - Ate donuts on people's birthdays.
      - position: Data Analytics Internship
        dates: Feb 2022 - Aug 2022
        url: "https://www.ligentec.com/"
        company: Ligentec SA 
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Master's Degree in Business Information Systems and Data Analysis (MIAGE)
        college: Paris Dauphine University, Paris
        dates: 2022 - 2023
        thesis_title: "Survival analysis methods for detecting the risk of financial fragility"
        thesis_url: "#"
      - degree: Exchange Year - Artificial Intelligence
        college: ENSEIRB-MATMECA, Bordeaux INP, Bordeaux
        dates: 2021 - 2022
        #thesis_title: "Effect of humans on other humans: a study of human behavior."
        #thesis_url: "#"
      - degree: Data Engineer Degree
        college: National Institute of Posts and Telecommunications (INPT), Rabat
        dates: 2019 - 2021
      - degree: Classes Préparatoires aux Grandes Écoles (CPGE) (MP)
        college: Lycée Reda Slaoui, Agadir
        dates: 2017 - 2019
        thesis_title: "Convolutional neural networks for automatic driving of an autonomous vehicle"
        thesis_url: "#"
#  publication:
#    title: Publications
#    icon: fas fa-book
#    format:
#      - date
#      - title
#      - authors
#      - journal
#    types:
#      - Journal Articles
#      - Proceedings
#    list:
#      - title: >-
#          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
#          eiusmod tempor incididunt ut labore et dolore magna aliqua.
#        authors: "F Last, F Second, P secondary"
#        date: "2018"
#        journal: "Journal of Field 52 (16), 9033-9044"
#        url: "#"
#        type: Journal Articles
#      - title: >-
#          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
#          eiusmod tempor incididunt ut labore et dolore magna aliqua.
#        authors: "F Last, F Second, P secondary"
#        date: "2018"
#        journal: "Journal of Field 52 (16), 9033-9044"
#        url: "#"
#        type: Journal Articles
#      - title: >-
#          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
#          eiusmod tempor incididunt ut labore et dolore magna aliqua.
#        authors: "F Last, F Second, P secondary"
#        date: "2018"
#        journal: "Journal of Field 52 (16), 9033-9044"
#        url: "#"
#        type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: ChatSage
        url: "https://kouhoumed.com/blog/chatsage/"
        description: ChatSage is a multi-model chatbot application that allows users to interact with various language models including GPT-3, GPT-4, Claude, and custom models.
      - title: Connected Components Search in a Graph
        url: "#"
        description: Implementation of the "CCF Fast and scalable connected component computation in MapReduce" algorithm with PySpark and DataBricks on GCP using Google Web Graph data.
      - title: SSL Junior ~ Enseirb IA
        url: "#"
        description: Development of an AI to pilot robots for an SSL Socker Junior team for the Robocup competition. Use of DDPG (reinforcement learning) architecture and a simulator for robot training and strategy.
      - title: Web scraping project for Avito.ma
        url: "#"
        description: Extraction of ad data from the avito.ma website with BeautifulSoup, cleaning and transformation of this data, creation of an analytical study of prices and highlighting of real estate price trends, presentation on dashboards.
      - title: Convolutional Neural Network for Self-driving Cars
        url: "#"
        description: Training a convolutional neural network to drive an autonomous car
      - title: Soccer player performance analysis
        url: "#"
        description: Comprehensive BI project for analyzing soccer player performance
      - title: Disaster detection on Twitter
        url: "#"
        description: NLP for sentiment analysis of tweets collected from a Twitter API. The aim was to detect whether a tweet was about a disaster or not.
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Python
        skillrating: 90
      - skill: R
        skillrating: 70
      - skill: SQL
        skillrating: 80
      - skill: Java
        skillrating: 60
      - skill: PySpark 
        skillrating: 60
      - skill: GCP
        skillrating: 60
      - skill: Power BI
        skillrating: 80
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Running
      - hobby: Reading
      - hobby: Video Games
      - hobby: Cooking
